### ISSUE TITLE
Add encryption to guestData on bookUnit() in WTUser lib

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-js-libs#26] opened 2017-08-07 09:53 UTC
The bookUnit function should receive an array of emails registered on the WTKeyRegistry that can decrypt the data, inside the function the WTKey lib should be use to encrypt that information between teh desired parties.

**Comment by JirkaChadima** [comment] 2018-03-13 11:02
Closing this as dupe of #60

**Closed by JirkaChadima** 2018-03-13 11:02 UTC
